import {
  LayoutDashboard,
  Settings,
  FileText,
  ShieldCheck,
  FileCog,
  BadgeAlert,
  Landmark,
  Download,
  FolderArchive,
  BookUser,
  CheckSquare,
  Ban,
  MessageSquare,
  Wheat,
  Send,
  Banknote,
  PiggyBank,
} from 'lucide-react';

export const allMenuItems = [
  {
    path: '/admin',
    label: 'Dashboard',
    icon: LayoutDashboard,
    roles: ['Super Admin', 'Loan Manager', 'Auditor', 'Loan Provider'],
  },
  {
    path: '/admin/reports',
    label: 'Reports',
    icon: FileText,
    roles: ['Super Admin', 'Loan Manager', 'Auditor', 'Loan Provider', 'Reconciliation'],
  },
   {
    path: '/admin/approvals',
    label: 'Approvals',
    icon: CheckSquare,
    roles: ['Super Admin', 'Loan Manager'],
  },
  {
    path: '/admin/reversals',
    label: 'Reversals',
    icon: FolderArchive,
    roles: ['Super Admin', 'Loan Manager'],
  },
  {
    path: '/admin/reversal-approvals',
    label: 'Reversal Approval',
    icon: CheckSquare,
    roles: ['Super Admin', 'Loan Manager'],
  },
  {
    path: '/admin/pending-payments',
    label: 'Pending Payments',
    icon: Download,
    roles: ['Super Admin', 'Loan Manager'],
  },
  {
    path: '/admin/pending-payment-approvals',
    label: 'Payment Approvals',
    icon: CheckSquare,
    roles: ['Super Admin', 'Loan Manager'],
  },
  {
    path: '/admin/npl',
    label: 'NPL',
    icon: BadgeAlert,
    roles: ['Super Admin', 'Loan Manager', 'Auditor'],
  },
  {
    path: '/admin/npl-collection',
    label: 'NPL Collection',
    icon: Banknote,
    roles: ['Super Admin', 'Loan Manager', 'Auditor'],
  },
  {
    path: '/admin/sms-management',
    label: 'SMS Management',
    icon: MessageSquare,
    roles: ['Super Admin', 'Loan Manager'],
  },
   {
    path: '/admin/access-control',
    label: 'Access Control',
    icon: ShieldCheck,
    roles: ['Super Admin'],
  },
  {
    path: '/admin/credit-score-engine',
    label: 'Scoring Engine',
    icon: FileCog,
    roles: ['Super Admin', 'Loan Manager'],
  },
  {
    path: '/admin/tax',
    label: 'Tax',
    icon: Landmark,
    roles: ['Super Admin', 'Loan Manager'],
  },
  {
    path: '/admin/tax-transfers',
    label: 'Tax Transfers',
    icon: Send,
    roles: ['Super Admin', 'Loan Manager'],
  },
  {
    path: '/admin/revolving-fund',
    label: 'Revolving Fund',
    icon: PiggyBank,
    roles: ['Super Admin', 'Loan Manager'],
  },
  {
    path: '/admin/settings',
    label: 'Settings',
    icon: Settings,
    roles: ['Super Admin', 'Loan Manager', 'Loan Provider'],
  },
  {
    path: '/admin/disbursement-control',
    label: 'Disbursement Control',
    icon: Ban,
    roles: ['Super Admin'],
  },
  {
    path: '/admin/audit-logs',
    label: 'Audit Logs',
    icon: BookUser,
    roles: ['Super Admin', 'Auditor'],
  },
  {
    path: '/admin/farmer-loans',
    label: 'Farmer Loans',
    icon: Wheat,
    roles: ['Super Admin', 'Loan Manager'],
  },
];
